repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/client9/misspell
    rev: v0.3.4
    hooks:
      - id: misspell
        args: [-locale=US]

  - repo: local
    hooks:
      - id: go-err-check
        name: errcheck
        description: Check for unchecked errors in Go code
        entry: errcheck
        language: system
        types: [go]
        pass_filenames: false
        args: [./...] 